steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/main-reducer-392717/laravel-app:latest", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/main-reducer-392717/laravel-app:latest"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "laravel-cloud-run-service"
      - "--image"
      - "gcr.io/main-reducer-392717/laravel-app:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
      - "--allow-unauthenticated"
      # Ajuste essas variáveis conforme necessário no console do GCP
      - "--set-env-vars"
      - "APP_KEY=${_APP_KEY},DB_CONNECTION=mysql,DB_SOCKET=/cloudsql/${_INSTANCE_CONNECTION_NAME},DB_DATABASE=${_DB_DATABASE},DB_USERNAME=${_DB_USERNAME},DB_PASSWORD=${_DB_PASSWORD}"

images:
  - "gcr.io/main-reducer-392717/laravel-app:latest"

substitutions:
  _APP_KEY: "base64:..." # Será substituído pelo Cloud Build Trigger
  _INSTANCE_CONNECTION_NAME: "project:region:instance"
